-- MySQL Script generated by MySQL Workbench
-- 10/01/15 07:29:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shopping_cart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopping_cart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping_cart` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `shopping_cart` ;

-- -----------------------------------------------------
-- Table `shopping_cart`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`session` (
  `sess_id` VARCHAR(32) NOT NULL COMMENT '',
  `valid_until` INT NOT NULL COMMENT '',
  `sess_data` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`sess_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL DEFAULT 'user' COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'open' COMMENT '',
  `buyer_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`order_id`)  COMMENT '',
  INDEX `fk_orders_users_idx` (`buyer_id` ASC)  COMMENT '',
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `shopping_cart`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`promotions` (
  `promotion_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `discount` INT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`promotion_id`)  COMMENT '',
  INDEX `fk_promotions_users1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_promotions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shopping_cart`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `desciption` MEDIUMTEXT NULL COMMENT '',
  `price` DECIMAL NOT NULL COMMENT '',
  `order_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `promotion_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '',
  INDEX `fk_products_orders1_idx` (`order_id` ASC)  COMMENT '',
  INDEX `fk_products_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_products_promotions1_idx` (`promotion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_products_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `shopping_cart`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shopping_cart`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_promotions1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `shopping_cart`.`promotions` (`promotion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`category_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`products_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`products_categories` (
  `product_id` INT NOT NULL COMMENT '',
  `category_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`product_id`, `category_id`)  COMMENT '',
  INDEX `fk_products_has_categories_categories1_idx` (`category_id` ASC)  COMMENT '',
  INDEX `fk_products_has_categories_products1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_products_has_categories_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopping_cart`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shopping_cart`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
